// This file is auto generated by polygo
package routes

import (
	"log"
	"os"
	"time"

	"github.com/MarcelArt/formigo/config"
	"github.com/MarcelArt/formigo/database"
	"github.com/MarcelArt/formigo/middlewares"
	"github.com/MarcelArt/formigo/repositories"
	api_routes "github.com/MarcelArt/formigo/routes/api"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/monitor"
	"github.com/gofiber/swagger"
)

func SetupRoutes(app *fiber.App) {
	app.Use(cors.New())

	file, err := os.OpenFile("./multi-tenant-system.log", os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if err != nil {
		log.Fatalf("error opening file: %v", err)
	}

	app.Use(limiter.New(limiter.Config{
		Max:        20,
		Expiration: 30 * time.Second,
	}))

	if config.Env.ServerENV != "prod" {
		app.Get("/swagger/*", swagger.HandlerDefault)     // default
		app.Get("/swagger/*", swagger.New(swagger.Config{ // custom
			URL:         "http://example.com/doc.json",
			DeepLinking: false,
		}))
	}

	app.Get("/metrics", monitor.New())

	authMiddleware := middlewares.NewAuthMiddleware(repositories.NewUserRepo(database.GetDB()))

	api := app.Group("/api")
	api.Use(logger.New(logger.Config{
		Output:     file,
		Format:     "[${time}] ${status} - ${method} ${path} - Query: ${queryParams} - Request: ${body} - Response: ${resBody}\n",
		TimeFormat: "2006-01-02 15:04:05",
		TimeZone:   "Local",
	}))
	api.Use(logger.New(logger.Config{
		Format:     "[${time}] ${status} - ${method} ${path} - Query: ${queryParams} - Request: ${body} - Response: ${resBody}\n",
		TimeFormat: "2006-01-02 15:04:05",
		TimeZone:   "Local",
	}))

	api_routes.SetupUserRoutes(api, authMiddleware)
	api_routes.SetupOrganizationRoutes(api, authMiddleware)
	api_routes.SetupUserOrganizationRoutes(api, authMiddleware)
	api_routes.SetupRoleRoutes(api, authMiddleware)
	api_routes.SetupUserRoleRoutes(api, authMiddleware)
	api_routes.SetupRolePermissionRoutes(api, authMiddleware)
	api_routes.SetupFormTemplateRoutes(api, authMiddleware)
}
