/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationSettingRouteImport } from './routes/organization.setting'
import { Route as OrganizationCreateRouteImport } from './routes/organization.create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingRoute = OrganizationSettingRouteImport.update({
  id: '/organization/setting',
  path: '/organization/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationCreateRoute = OrganizationCreateRouteImport.update({
  id: '/organization/create',
  path: '/organization/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/setting': typeof OrganizationSettingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/setting': typeof OrganizationSettingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/setting': typeof OrganizationSettingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/organization/create'
    | '/organization/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/organization/create'
    | '/organization/setting'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/organization/create'
    | '/organization/setting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OrganizationCreateRoute: typeof OrganizationCreateRoute
  OrganizationSettingRoute: typeof OrganizationSettingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/setting': {
      id: '/organization/setting'
      path: '/organization/setting'
      fullPath: '/organization/setting'
      preLoaderRoute: typeof OrganizationSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/create': {
      id: '/organization/create'
      path: '/organization/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof OrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OrganizationCreateRoute: OrganizationCreateRoute,
  OrganizationSettingRoute: OrganizationSettingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
